#Expyriment 0.10.0 (Python 3.7.6), .xpe-file, coding: UTF-8
#date: Mon Jan 09 2023 16:32:25
#sha1: 156cf5
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='is153802', release='5.15.0-48-generic', version='#54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
221,stdout,received,'Warning: Failed to find font Inconsolata.ttf!'
221,stderr,received,'Traceback (most recent call last):'
221,stderr,received,'  File "/home/is153802/.pyenv/versions/expyriment/lib/python3.7/site-packages/expyriment/stimuli/_textline.py", line 100, in __init__'
222,stderr,received,"    with open(self._text_font, 'rb') as f:"
222,stderr,received,"FileNotFoundError: [Errno 2] No such file or directory: ''"
222,stderr,received,'During handling of the above exception, another exception occurred:'
222,stderr,received,'Traceback (most recent call last):'
222,stderr,received,'  File "expy_read_lpp.py", line 83, in <module>'
222,stderr,received,'    expyriment.control.initialize(exp)'
222,stderr,received,'  File "/home/is153802/.pyenv/versions/expyriment/lib/python3.7/site-packages/expyriment/control/_experiment_control.py", line 474, in initialize'
223,stderr,received,'    position=(0, -5))'
223,stderr,received,'  File "/home/is153802/.pyenv/versions/expyriment/lib/python3.7/site-packages/expyriment/stimuli/_textline.py", line 103, in __init__'
223,stderr,received,'    raise IOError("Font \'{0}\' not found!".format(text_font))'
223,stderr,received,"OSError: Font 'Inconsolata.ttf' not found!"
